spring:
  profiles:
    active: dev
  application:
    name: springboot-otel
  jackson:
    date-format: "yyyy-MM-dd HH:mm:ss"
    time-zone: GMT+8
    property-naming-strategy: SNAKE_CASE

otel:
  traces:
    exporter: none
  metrics:
    exporter: none
  logs:
    exporter: none

